[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "1"
path = "src/1.rs"

[[bin]]
name = "2"
path = "src/2.rs"

[[bin]]
name = "3"
path = "src/3.rs"

[[bin]]
name = "4"
path = "src/4.rs"

[dependencies]
itertools = "0.12.0"
regex = "1.10.2"
